// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'TheFooter': typeof import("../components/TheFooter.vue")['default'],
    'TheHeader': typeof import("../components/TheHeader.vue")['default'],
    'TheHome': typeof import("../components/TheHome.vue")['default'],
    'TheNav': typeof import("../components/TheNav.vue")['default'],
    'TheSidebar': typeof import("../components/TheSidebar.vue")['default'],
    'HomePageMangaFeatured': typeof import("../components/HomePage/MangaFeatured.vue")['default'],
    'HomePageMangeNewUpdate': typeof import("../components/HomePage/MangeNewUpdate.vue")['default'],
    'HomePageSpotlight': typeof import("../components/HomePage/Spotlight.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'ColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'LazyTheFooter': typeof import("../components/TheFooter.vue")['default'],
    'LazyTheHeader': typeof import("../components/TheHeader.vue")['default'],
    'LazyTheHome': typeof import("../components/TheHome.vue")['default'],
    'LazyTheNav': typeof import("../components/TheNav.vue")['default'],
    'LazyTheSidebar': typeof import("../components/TheSidebar.vue")['default'],
    'LazyHomePageMangaFeatured': typeof import("../components/HomePage/MangaFeatured.vue")['default'],
    'LazyHomePageMangeNewUpdate': typeof import("../components/HomePage/MangeNewUpdate.vue")['default'],
    'LazyHomePageSpotlight': typeof import("../components/HomePage/Spotlight.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'LazyColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
  }
}
export const TheFooter: typeof import("../components/TheFooter.vue")['default']
export const TheHeader: typeof import("../components/TheHeader.vue")['default']
export const TheHome: typeof import("../components/TheHome.vue")['default']
export const TheNav: typeof import("../components/TheNav.vue")['default']
export const TheSidebar: typeof import("../components/TheSidebar.vue")['default']
export const HomePageMangaFeatured: typeof import("../components/HomePage/MangaFeatured.vue")['default']
export const HomePageMangeNewUpdate: typeof import("../components/HomePage/MangeNewUpdate.vue")['default']
export const HomePageSpotlight: typeof import("../components/HomePage/Spotlight.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const LazyTheFooter: typeof import("../components/TheFooter.vue")['default']
export const LazyTheHeader: typeof import("../components/TheHeader.vue")['default']
export const LazyTheHome: typeof import("../components/TheHome.vue")['default']
export const LazyTheNav: typeof import("../components/TheNav.vue")['default']
export const LazyTheSidebar: typeof import("../components/TheSidebar.vue")['default']
export const LazyHomePageMangaFeatured: typeof import("../components/HomePage/MangaFeatured.vue")['default']
export const LazyHomePageMangeNewUpdate: typeof import("../components/HomePage/MangeNewUpdate.vue")['default']
export const LazyHomePageSpotlight: typeof import("../components/HomePage/Spotlight.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const componentNames: string[]
